# Generated by Django 5.0.5 on 2025-06-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(default='1234567890'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='products/'),
        ),
    ]
