# Generated by Django 5.0.5 on 2025-06-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0002_user_address_user_phone_no_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
