# Generated by Django 5.0.5 on 2025-06-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
