# Generated by Django 5.0.5 on 2025-06-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwear', '0004_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
    ]
